use std::{
	env,
	fs::{self, File},
	io::Write,
	path::Path
};

/// Count create_test! invocations in source files recursively.
fn count_tests_in_source(path: &Path) -> usize {
	let mut count = 0;

	let entries = match fs::read_dir(path) {
		Ok(e) => e,
		Err(_) => return 0
	};

	for entry in entries {
		let entry = entry.expect("read_dir entry");
		let path = entry.path();

		if path.is_dir() {
			count += count_tests_in_source(&path);
		} else if path.extension().and_then(|e| e.to_str()) == Some("rs") {
			let src = fs::read_to_string(&path).unwrap_or_default();
			count += src.match_indices("create_test!(").count();
		}
	}

	count
}

/// Recursively find all ELF files under build/userspace.
fn search_userspace_elfs(path: &Path) -> Vec<(String, String)> {
	let manifest_dir = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR not set");
	let mut elfs: Vec<(String, String)> = Vec::new();

	fn recurse(dir: &Path, manifest_dir: &str, out: &mut Vec<(String, String)>) {
		for entry in fs::read_dir(dir).expect("failed to read userspace dir") {
			let entry = entry.expect("read_dir entry");
			let path = entry.path();

			if path.is_dir() {
				recurse(&path, manifest_dir, out);
				continue;
			}

			if path.extension().and_then(|e| e.to_str()) != Some("elf") {
				continue;
			}

			let stem = match path.file_stem().and_then(|s| s.to_str()) {
				Some(s) => s.to_string(),
				None => continue
			};

			let parent_name = match path
				.parent()
				.and_then(|p| p.file_name())
				.and_then(|s| s.to_str())
			{
				Some(s) => s.to_string(),
				None => continue
			};

			if stem != parent_name {
				continue;
			}

			let rel = path
				.strip_prefix(manifest_dir)
				.unwrap_or(&path)
				.to_string_lossy()
				.replace('\\', "/");

			out.push((stem, rel));
		}
	}

	if path.exists() {
		recurse(path, &manifest_dir, &mut elfs);
	}

	elfs.sort_by(|a, b| a.0.cmp(&b.0));
	elfs
}

fn write_userspace_registry(out_dir: &Path, elfs: &[(String, String)]) {
	let out_path = out_dir.join("userspace_registry.rs");
	let mut f = File::create(&out_path).expect("could not create userspace_registry.rs in OUT_DIR");

	writeln!(f, "// auto-generated by build.rs").unwrap();
	writeln!(f, "#[derive(Clone, Copy)]").unwrap();
	writeln!(f, "pub(crate) struct UserspaceElf {{").unwrap();
	writeln!(f, "    pub name: &'static str,").unwrap();
	writeln!(f, "    pub bytes: &'static [u8],").unwrap();
	writeln!(f, "}}").unwrap();

	writeln!(f, "pub(crate) static USERSPACE_ELFS: &[UserspaceElf] = &[").unwrap();
	for (name, rel) in elfs {
		writeln!(
			f,
			"    UserspaceElf {{ name: {:?}, bytes: include_bytes!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/{}\")) }},",
			name,
			rel
		)
		.unwrap();
	}
	writeln!(f, "];").unwrap();

	println!(
		"cargo:warning=generated {} userspace ELF refs -> {}",
		elfs.len(),
		out_path.display()
	);
}

fn main() {
	let out_dir = env::var("OUT_DIR").expect("OUT_DIR not set");
	let out_dir = Path::new(&out_dir);

	println!("cargo:rerun-if-changed=build/userspace");
	println!("cargo:rerun-if-changed=src");

	// Count tests in source and warn if it looks like some may be stripped.
	let src = Path::new("src");
	let test_count = count_tests_in_source(src) - 4; // currently the 4 are the three comments in build.rs and one in ktest.rs
	println!(
		"cargo:warning=found {} create_test!() invocations in source",
		test_count
	);

	let userspace_root = Path::new("build/userspace");
	let elfs = search_userspace_elfs(userspace_root);
	write_userspace_registry(out_dir, &elfs);
}
