style_edition = "2024"
unstable_features = true

indent_style = "Block"
reorder_imports = true
format_code_in_doc_comments = true
hard_tabs = true
imports_indent = "Block"
imports_layout = "HorizontalVertical"
merge_derives = true
imports_granularity = "Crate"
#newline_style = "Auto"
normalize_doc_attributes = true
overflow_delimited_expr = true
remove_nested_parens = true
reorder_impl_items = true
group_imports = "StdExternalCrate"
reorder_modules = true
space_after_colon = true
struct_lit_single_line = false
tab_spaces = 4
trailing_comma = "Never"
trailing_semicolon = false
type_punctuation_density = "Wide"
use_field_init_shorthand = true
use_try_shorthand = true
where_single_line = false
wrap_comments = true